name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - uses: actions/checkout@v3
    
#    - name: Build and push docker image
#      uses: mr-smithers-excellent/docker-build-push@v4
#      with: 
#        image: francislainy/mbbackend
#        tag: latest
#        registry: docker.io
#        username: ${{ secrets.DOCKERHUB_USERNAME }}
#        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Pull
      run: docker pull francislainy/mbbackend:latest
    - name: Run tests
      uses: addnab/docker-run-action@v3
      with:
        image: francislainy/mbbackend:latest
        run: |
             docker run -it --entrypoint=entrypoint.sh francislainy/mbbackend:latest
             docker run --privileged --entrypoint=entrypoint.sh --rm -v ${PWD}:/project francislainy/mbbackend:latest ../mvnw test
          

    
    
    
#    - name: Run tests
#      run: docker run --privileged --entrypoint=entrypoint.sh --rm -v ${PWD}:/project francislainy/mbbackend ./mvnw test



#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag mbbackend:test
#    - name: Push the docker image
#      run: docker push mbbackend:test
#    - name: Run tests
#      run: docker run --privileged --entrypoint=entrypoint.sh --rm -v ${PWD}:/project mbbackend:test ./mvnw test
