name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mbbackend:${{steps.vars.outputs.tag}}
    - name: Push the docker image
      run: docker push mbbackend:${{steps.vars.outputs.tag}}
    - name: Run tests
      run: docker run --privileged --entrypoint=entrypoint.sh --rm -v ${PWD}:/project mbbackend ./mvnw test
